### ISSUE TITLE
How does it boot from the NVMe?

### ISSUE THREAD

**Issue by eehlers** [inindev/nanopi-r6#4]
My understanding is that the R6C is not capable of booting from the NVMe.  In your build "booting from internal NVMe", I take it you boot from the internal eMMC, and then load the root filesystem from the NVMe?  How is this accomplished?  I note that this build uses a custom u-boot.  Have you modified u-boot to load the root filesystem from the NVMe?  What is the origin of this u-boot image?

**Comment by inindev** [comment]
u-boot needs to be bootstrapped from SPI flash or sdmmc / emmc.  u-boot can then load linux from NVMe.

**Comment by eehlers** [comment]
Many thanks for getting back to me.  Could you please elaborate?  The u-boot shipped by FriendlyElec, am I correct in thinking that it does not load from NVMe?  Did you patch it?  Again, what is the origin of the u-boot image that you are distributing?

**Comment by inindev** [comment]
The point of this repo is to run upstream debian linux on the nanopi-r6c.  I do not have experience with Rockchip's 2017 downstream patched u-boot.  The v2024.01-rc5 u-boot supplied here: https://github.com/inindev/nanopi-r6/releases
will boot a linux image from an m.2 nvme flash.  I only tested with a Samsung 980 NVMe.

A quick search turned up this article which does a good job further explaining u-boot and its role:

U-Boot
Unfortunately, our CPU’s boot ROM can’t directly load our kernel. Linux has to be invoked in a specific way to obtain boot arguments and a pointer to the device tree and initrd, and it also expects that main memory has already been initialized. Boot ROMs also don’t know how to initialize main memory, so we would have nowhere to store Linux. Also, boot ROMs tend to just load a few KB from flash at the most — not enough to house an entire kernel. So, we need a small program that the boot ROM can load that will initialize our main memory and then load the entire (usually-multi-megabyte) Linux kernel and then execute it.

The most popular bootloader for embedded systems, Das U-Boot, does all of that — but adds a ton of extra features. It has a fully interactive shell, scripting support, and USB/network booting.

If you’re using a tiny SPI flash chip for booting, you’ll probably store your kernel, device tree, and initrd / root filesystem at different offsets in raw flash — which U-Boot will gladly load into RAM and execute for you. But since it also has full filesystem support, so you could store your kernel and device tree as normal files on a partition of an SD card, eMMC device, or on a USB flash drive.

U-Boot has to know a lot of technical details about your system. There’s a dedicated board.c port for each supported platform that initializes clocks, DRAM, and relevant memory peripherals, along with initializing any important peripherals, like your UART console or a PMIC that might need to be configured properly before bringing the CPU up to full speed. Newer board ports often store at least some of this configuration information inside a Device Tree, which we’ll talk about later. Some of the DRAM configuration data is often autodetected, allowing you to change DRAM size and layout without altering the U-Boot port’s code for your processor ((If you have a DRAM layout on the margins of working, or you’re using a memory chip with very different timings than the one the port was built for, you may have to tune these values)). You configure what you want U-Boot to do by writing a script that tells it which device to initialize, which file/address to load into which memory address, and what boot arguments to pass along to Linux. While these can be hard-coded, you’ll often store these names and addresses as environmental variables (the boot script itself can be stored as a bootcmd environmental variable). So a large part of getting U-Boot working on a new board is working out the environment.

https://jaycarlson.net/embedded-linux/

**Comment by eehlers** [comment]
Thank you.
